export const S = {
  app: {
    name: 'Menzi',
    signOut: 'Sign out',
  },
  auth: {
    signInTitle: 'Sign in',
    signIn: 'Sign in',
    registerTitle: 'Create an account',
    createAccount: 'Create an account',
    backToSignIn: 'Back to sign in',
    forgotTitle: 'Reset your password',
    forgotPassword: 'Forgot your password?',
    sendResetLink: 'Send a reset link',
    resetSent: 'If that address has an account, a reset link is on its way.',
    resetTitle: 'Choose a new password',
    resetMissingToken: 'This reset link is incomplete. Request a new one.',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    saveNewPassword: 'Save the new password',
    passwordsDoNotMatch: 'The two passwords do not match.',
    passwordTooShort: 'The password must be at least {minimum} characters.',
    passwordLength: 'At least {minimum} characters ({current} so far)',
    email: 'Email address',
    name: 'Name',
    password: 'Password',
    or: 'or',
    continueWith: 'Continue with {provider}',
    completingSignIn: 'Finishing sign in',
    registrationClosed:
      'This deployment is not accepting new accounts. Ask an administrator for an invitation.',
    signOutEverywhere: 'Sign out everywhere',
    accountHeading: 'Account',
    noEmail: 'No email on this account',
    passwordHeading: 'Password',
    currentPassword: 'Current password',
    passwordChanged: 'Your password was changed.',
    noPassword:
      'This account signs in with a provider, so it has no password to change.',
    devicesHeading: 'Signed in devices',
    thisDevice: 'This device',
    unknownDevice: 'Unknown device',
    lastSeen: 'Last seen {when}',
    revoke: 'Sign out',
    deviceRevoked: 'That device was signed out.',
    deviceRevokeFailed: 'Could not sign that device out',
  },
  theme: {
    system: 'Auto',
    light: 'Light',
    dark: 'Dark',
  },
  workspace: {
    ready: 'Workspace ready',
    settingUp: 'Setting up your workspace — this takes about 30 seconds.',
    settingUpElapsed: 'Still setting up ({elapsed}). This can take a couple of minutes.',
    slowHint: 'You can keep browsing while this finishes.',
    pauseHint: 'Your workspace is paused. Starting a session will wake it.',
    notNow: 'Not now',
    failedTitle: 'Workspace setup failed',
    retry: 'Try again',
    notAMemberTitle: 'No workspace for you in this project',
    notAMemberBody:
      'Ask a project maintainer for access if you need an agent to work on it.',
    unreachable: "Can't reach the workspace service.",
    reasons: {
      'setting-up': 'Your workspace is still being set up.',
      failed: 'The workspace could not be set up.',
      paused: 'Your workspace is paused.',
      'not-permitted': 'You do not have access to a workspace in this project.',
      unreachable: "Can't reach the workspace service.",
      absent: 'There is no workspace for this project yet.',
      loading: 'Checking your workspace.',
    },
    card: {
      title: 'Workspace',
      none: 'No workspace yet',
      noneBody: 'One is set up when you open a session in this project.',
      columns: {
        status: 'Status',
        instance: 'Container',
        created: 'Created',
        actions: 'Actions',
      },
      actions: {
        pause: 'Pause',
        resume: 'Resume',
        delete: 'Delete',
      },
      statuses: {
        requested: 'Setting up',
        provisioning: 'Setting up',
        ready: 'Ready',
        running: 'In use',
        idle: 'Paused',
        archived: 'Archived',
        deleted: 'Deleted',
      },
      deleteTitle: 'Delete this workspace?',
      deleteBody:
        'The container and every change in it are removed. This cannot be undone.',
      deleteConfirm: 'Delete workspace',
      deleteCancel: 'Keep it',
      toasts: {
        paused: 'The workspace is paused.',
        resumed: 'The workspace is running.',
        deleted: 'The workspace was deleted.',
        failed: 'That did not work.',
      },
    },
    sessions: {
      emptyTitle: 'No sessions yet',
      emptyBody:
        'This project has its own agent, so sessions here do not share state with anything else.',
    },
  },
  nav: {
    projects: 'Projects',
    needsYou: 'Needs you',
    settings: 'Settings',
  },
  notFound: {
    title: 'Page not found',
    body: 'The page you are looking for does not exist or has moved.',
    goToProjects: 'Go to projects',
  },
  unavailable: {
    title: 'Not available yet',
    body: 'This screen needs a backend service that has not landed yet. It will appear here once the service is live.',
  },
  dataState: {
    loading: 'Loading',
    retry: 'Try again',
    errorTitle: 'Something went wrong',
    emptyTitle: 'Nothing here yet',
  },
  errorBoundary: {
    title: 'Something went wrong',
    unknownError: 'Unknown error',
    dismiss: 'Dismiss',
  },
  previews: {
    title: 'Previews',
    create: 'Create preview',
    emptyTitle: 'No previews yet',
    emptyBody: 'Create a preview to get a live environment for a commit or branch.',
    columns: {
      status: 'Status',
      mode: 'Mode',
      branch: 'Branch',
      created: 'Created',
      actions: 'Actions',
    },
    branchDefault: 'No branch',
    statuses: {
      starting: 'Starting',
      ready: 'Ready',
      failed: 'Failed',
      terminated: 'Terminated',
    },
    modes: {
      pinned: 'Pinned',
      live: 'Live',
    },
    actions: {
      menu: 'Actions',
      reset: 'Reset',
      restart: 'Restart',
      teardown: 'Tear down',
    },
    toasts: {
      title: 'Preview action failed',
      created: 'Preview created.',
      resetStarted: 'Preview reset started.',
      restartStarted: 'Preview restart started.',
      tornDown: 'Preview torn down.',
    },
    confirmations: {
      teardownTitle: 'Tear down preview',
      teardownBody: 'This stops the preview environment and its services. Source control and branch data are not affected.',
      cancel: 'Cancel',
      confirm: 'Tear down',
      resetTitle: 'Reset preview',
      resetBody: 'This rebuilds the preview environment from its pinned state.',
    },
  },
  session: {
    title: 'Session',
    threads: {
      title: 'Threads',
      emptyTitle: 'No threads yet',
      emptyBody: 'Threads appear once the session service streams a conversation.',
    },
    conversation: {
      emptyTitle: 'No conversation yet',
      emptyBody: 'The session service is not connected, so no messages can be shown.',
    },
    composer: {
      placeholder: 'Send a message to the agent',
      send: 'Send',
      mode: 'Mode',
      queue: 'Queue',
      steer: 'Steer',
      disabled: 'The session service is not connected.',
    },
  },
  env: {
    title: 'Environment',
    environmentLabel: 'Environment name',
    environmentHelp: 'The name of the environment spec registered with the orchestrator.',
    refresh: 'Refresh',
    launch: 'Launch',
    relaunch: 'Relaunch',
    status: {
      ready: 'Ready',
      degraded: 'Degraded',
      unknown: 'Unknown',
    },
    health: {
      healthy: 'Healthy',
      degraded: 'Degraded',
    },
    columns: {
      component: 'Component',
      status: 'Status',
      health: 'Health',
      logs: 'Logs',
    },
    exposures: {
      title: 'Exposures',
      emptyBody: 'This environment exposes no ports.',
    },
    logs: {
      title: 'Logs',
      emptyBody: 'No log lines have been recorded for this component.',
      view: 'View logs',
    },
    launchResult: {
      success: 'Environment launched.',
      failure: 'Environment launch did not complete.',
    },
    relaunchResult: {
      success: 'Environment relaunched.',
      unchanged: 'No component changed, so nothing was restarted.',
    },
    specMissingTitle: 'Environment spec not registered',
    specMissingBody: 'The orchestrator has no spec with this name. Register one through the supervisor before opening the environment.',
  },
  transcript: {
    title: 'Conversation',
    emptyTitle: 'No conversation yet',
    emptyBody: 'Nothing has been recorded for this session yet.',
    disconnectedTitle: 'Session stream interrupted',
    disconnectedBody: 'The session proxy is not reachable, so live events are paused. Reconnect to resume from the last sequence.',
    reconnect: 'Reconnect',
    columns: {
      sequence: 'Seq',
      type: 'Type',
      payload: 'Payload',
    },
    status: {
      live: 'Live',
      loading: 'Loading history',
      reconnecting: 'Reconnecting',
      idle: 'Not connected',
    },
  },
  projectsFirstOrg: {
    firstOrgTitle: 'Create an organisation',
    firstOrgBody:
      'Projects live in an organisation. Create one to get started.',
    orgName: 'Name',
    orgSlug: 'Identifier',
    createOrg: 'Create organisation',
  },
  projects: {
    selector: {
      label: 'Project',
      searchPlaceholder: 'Search projects',
      loading: 'Loading projects',
      empty: 'No projects yet. Create one to get started.',
      unavailable: 'Projects could not be loaded.',
    },
    title: 'Projects',
    description: 'Every project you have access to, across all orgs.',
    searchLabel: 'Search projects',
    searchPlaceholder: 'Search by name or slug',
    filterLabel: 'Filter by org',
    filterAll: 'All orgs',
    create: 'New project',
    createTitle: 'Create a project',
    emptyTitle: 'No projects yet',
    emptyBody: 'Create a project to get a workspace, previews and a place for agent sessions.',
    nameLabel: 'Name',
    slugLabel: 'Slug',
    descriptionLabel: 'Description',
    orgLabel: 'Org',
    columns: {
      name: 'Name',
      slug: 'Slug',
      org: 'Org',
      updated: 'Updated',
      actions: 'Actions',
    },
    actions: {
      open: 'Open',
      previews: 'Previews',
    },
    errors: {
      nameRequired: 'Enter a project name.',
      slugRequired: 'Enter a slug.',
      slugInvalid: 'Use lowercase letters, numbers and hyphens only.',
      orgRequired: 'Choose an org.',
      duplicateSlug: 'A project with this slug already exists in this org.',
    },
    toasts: {
      created: 'Project created.',
      failed: 'The project could not be created.',
    },
    detail: {
      previews: 'Previews',
      design: 'Design',
      environment: 'Environment',
      created: 'Created',
      updated: 'Updated',
      org: 'Org',
      slug: 'Slug',
    },
  },
  sections: {
    code: 'Code',
    design: 'Design',
    project: 'Project',
  },
  code: {
    newSession: 'New session',
    startFailed: 'The session could not be started.',
    emptyTitle: 'No sessions yet',
    emptyBody: 'Start a session to open an opencode conversation for this project.',
    pickTitle: 'Pick a session',
    pickBody: 'Choose a session tab above to read its transcript.',
    sessionsUnavailable: 'The session proxy is not reachable, so session tabs cannot be listed.',
  },
  chat: {
    title: 'Conversation',
    label: 'Message',
    placeholder: 'Ask the agent to change the code',
    send: 'Send',
    sending: 'Sending',
    sendFailed: 'The prompt could not be sent.',
    you: 'You',
    agent: 'Agent',
    emptyTitle: 'No messages yet',
    emptyBody: 'Send a prompt to start the conversation. The reply is streamed back from opencode.',
    jumpToLatest: 'Jump to latest',
    refreshing: 'Syncing',
    unknownError: 'The agent reported an error.',
  },
  review: {
    title: 'Code review',
    emptyTitle: 'No changes yet',
    emptyBody: 'File changes appear here as the agent edits the working tree.',
    noPatch: 'No textual diff is available for this file.',
    filesLabel: 'Changed files',
    repositoryRoot: 'Repository root',
    unknown: 'unknown',
    columns: {
      file: 'File',
      status: 'Status',
      additions: 'Added',
      deletions: 'Removed',
    },
  },
  chatSteps: {
    input: 'Input',
    result: 'Result',
    thinking: 'Thinking',
    showMore: 'Show more',
    showLess: 'Show less',
    noResult: 'No result was returned.',
    status: {
      streaming: 'Starting',
      running: 'Running',
      completed: 'Done',
      error: 'Failed',
    },
    compaction: {
      running: 'Compacting context',
      completed: 'Context compacted',
      error: 'Context compaction failed',
    },
  },
  admin: {
    title: 'Admin',
    tabs: {
      users: 'Users',
      quotas: 'Quotas',
      billing: 'Billing',
    },
    bodies: {
      users: 'User management',
      quotas: 'Quota management',
      billing: 'Billing management',
    },
  },
  settings: {
    title: 'Settings',
    tabs: {
      profile: 'Profile',
      modelAccounts: 'Model accounts',
      notifications: 'Notifications',
    },
    profile: {
      nameLabel: 'Name',
      emailLabel: 'Email',
      save: 'Save',
      saved: 'Profile saved.',
      errors: {
        nameRequired: 'Enter your name.',
        emailInvalid: 'Enter a valid email address.',
      },
    },
    modelAccounts: {
      intro: 'Add or manage your model provider accounts.',
      addAccount: 'Add account',
    },
    notifications: {
      intro: 'Choose how you want to be notified.',
      webPush: 'Web push',
      email: 'Email',
      chat: 'Chat',
      save: 'Save',
    },
  },
};