[package]
name = "menzi-workspace"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
menzi-common = { path = "../common" }
menzi-lxd = { path = "../lxd" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
axum.workspace = true
uuid.workspace = true
chrono.workspace = true
reqwest.workspace = true
async-trait.workspace = true
sqlx.workspace = true

[dev-dependencies]
tower.workspace = true
